# ---------------------------------------------
# Tamata Docker Compose for Rpi config Workshop
# ---------------------------------------------
# Rename to docker-compose.yml
# play with HYPRIOT-OS-32bits : https://blog.hypriot.com/downloads/
# Flash microSD with etcher: https://etcher.io/
version: '3.2'
services: 
#   portainer:
#     image: portainer/portainer:linux-arm
#     restart: always
#     ports:
#      - 9000:9000
#     volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer:/data
     
#   cloud:
#     image: valentinalexeev/rpi-cloudcmd
#     restart: always
#     ports:
#       - 8000:8000
#     volumes:
# #      - ~:/root
#       - project:/mnt/fs
  mosquitto:
    image: fstehle/rpi-mosquitto
    restart: always
    ports:
      - 1883:1883
     
  
volumes:
   # portainer:
   # postgres:
   # redis:
   # var:
   # project: